### ISSUE TITLE
taking so long

### ISSUE THREAD

**Issue by Mrdev88** [Looky1173/Scratch-Auth-Client#4] opened 2022-11-20 16:54 UTC
scratch auth is taking so long to load when I sign in

**Comment by Looky1173** [comment] 2022-11-20 16:57
Hi @Mrdev88, does this apply to one click sign in or the other sign in methods? Also, which website sent you to Scratch Auth? Was it Itinerary?

**Comment by Mrdev88** [comment] 2022-11-20 16:59
it was ocular

**Comment by Mrdev88** [comment] 2022-11-20 17:00
> Hi @Mrdev88, does this apply to one click sign in or the other sign in methods? Also, which website sent you to Scratch Auth? Was it Itinerary?

yes, it applies to one click sign in

**Comment by Looky1173** [comment] 2022-11-20 17:01
Hmm, for me, it only takes two seconds to sign in to Ocular with Scratch Auth. Could you please try signing in at https://beta.itinerary.eu.org/ too, and let me know how fast it goes?

**Comment by Mrdev88** [comment] 2022-11-20 17:02
it go's so fast

**Comment by Looky1173** [comment] 2022-11-20 17:03
Then I think the problem is on Ocular's end, not on Scratch Auth's. Perhaps it was just a temporary hiccup? Is signing in to Ocular still slow for you?

**Comment by Mrdev88** [comment] 2022-11-20 17:04
still slow

**Comment by Looky1173** [comment] 2022-11-20 17:04
How slow?

**Comment by Mrdev88** [comment] 2022-11-20 17:05
about 20 minutes

**Comment by Mrdev88** [comment] 2022-11-20 17:05
... still loading

**Comment by Mrdev88** [comment] 2022-11-20 17:05
still loading

**Comment by Mrdev88** [comment] 2022-11-20 17:06
this is taking so long

**Comment by Mrdev88** [comment] 2022-11-20 17:06
let me check the scratch auth status page

**Comment by Mrdev88** [comment] 2022-11-20 17:07
https://stats.uptimerobot.com/4Ggz4Fzo2O/791466611 no problems with the severs

**Comment by Mrdev88** [comment] 2022-11-20 17:08
it's still loading

**Comment by Looky1173** [comment] 2022-11-20 17:08
Could you try closing Scratch Auth and opening it in a new incognito browser tab?

**Comment by Mrdev88** [comment] 2022-11-20 17:10
ok

**Comment by Mrdev88** [comment] 2022-11-20 17:10
I'm in safari how to do that

**Comment by Looky1173** [comment] 2022-11-20 17:12
> I'm in safari how to do that

Here's an article I found that explains how to do it: https://www.avast.com/c-how-to-go-incognito-safari

**Closed as not planned** 2023-08-14 13:24 UTC
